-- CRIAÇÃO DO BANCO E ESTRUTURA FÍSICA 

IF DB_ID('CORE_BANK') IS NULL
BEGIN
    CREATE DATABASE CORE_BANK;
END
GO

ALTER DATABASE CORE_BANK ADD FILEGROUP RG_CADASTRO;
ALTER DATABASE CORE_BANK ADD FILEGROUP RG_ENDERECO;
ALTER DATABASE CORE_BANK ADD FILEGROUP RG_FINANCEIRO;
ALTER DATABASE CORE_BANK ADD FILEGROUP RG_TRANSACAO;
ALTER DATABASE CORE_BANK ADD FILEGROUP RG_AUDITORIA;
GO

ALTER DATABASE CORE_BANK 
ADD FILE (
    NAME = N'Cadastro_Data',
    FILENAME = N'C:\SQLData\Cadastro_Data.ndf',
    SIZE = 50MB,
    FILEGROWTH = 10MB
) TO FILEGROUP RG_CADASTRO;

ALTER DATABASE CORE_BANK 
ADD FILE (
    NAME = N'Endereco_Data',
    FILENAME = N'C:\SQLData\Endereco_Data.ndf',
    SIZE = 50MB,
    FILEGROWTH = 10MB
) TO FILEGROUP RG_ENDERECO;

ALTER DATABASE CORE_BANK 
ADD FILE (
    NAME = N'Financeiro_Data',
    FILENAME = N'C:\SQLData\Financeiro_Data.ndf',
    SIZE = 50MB,
    FILEGROWTH = 10MB
) TO FILEGROUP RG_FINANCEIRO;

ALTER DATABASE CORE_BANK 
ADD FILE (
    NAME = N'Transacao_Data',
    FILENAME = N'C:\SQLData\Transacao_Data.ndf',
    SIZE = 50MB,
    FILEGROWTH = 10MB
) TO FILEGROUP RG_TRANSACAO;

ALTER DATABASE CORE_BANK 
ADD FILE (
    NAME = N'Auditoria_Data',
    FILENAME = N'C:\SQLData\Auditoria_Data.ndf',
    SIZE = 50MB,
    FILEGROWTH = 10MB
) TO FILEGROUP RG_AUDITORIA;
GO
-- TABELAS DE DOMÍNIO 

USE CORE_BANK;
GO

CREATE TABLE TB_TIPO_PESSOA(
    ID_TIPO_PESSOA INT PRIMARY KEY,
    DS_TIPO_PESSOA VARCHAR(20) NOT NULL
);

CREATE TABLE TB_STATUS_CONTA(
    ID_STATUS_CONTA INT PRIMARY KEY,
    DS_STATUS_CONTA VARCHAR(20) NOT NULL
);

CREATE TABLE TB_TIPO_TRANSACAO(
    ID_TIPO_TRANSACAO INT PRIMARY KEY,
    DS_TIPO_TRANSACAO VARCHAR(20) NOT NULL
);

-- CARGA INICIAL DE DOMINIOS

INSERT INTO TB_TIPO_PESSOA VALUES (1, 'Física'), (2, 'Jurídica');
INSERT INTO TB_STATUS_CONTA VALUES (1, 'Ativa'), (2, 'Bloqueada'), (3, 'Encerrada');
INSERT INTO TB_TIPO_TRANSACAO VALUES (1, 'PIX'), (2, 'TED'), (3, 'DOC');
GO

-- CADASTRO E ENDERECO

CREATE TABLE TB_CLIENTE(
    ID_CLIENTE BIGINT PRIMARY KEY IDENTITY(1,1),
    NM_CLIENTE VARCHAR(50) NOT NULL,
    NR_CPF_CNPJ VARCHAR(18) NOT NULL UNIQUE,
    DT_NASCIMENTO DATE NOT NULL,
    ID_TIPO_PESSOA_FK INT FOREIGN KEY REFERENCES TB_TIPO_PESSOA(ID_TIPO_PESSOA),
    ST_ATIVO BIT DEFAULT 1
) ON RG_CADASTRO;

CREATE TABLE TB_ENDERECO(
    ID_ENDERECO BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE BIGINT FOREIGN KEY REFERENCES TB_CLIENTE(ID_CLIENTE), 
    DS_LOGRADOURO VARCHAR(250),
    NR_CEP VARCHAR(8),
    NM_CIDADE VARCHAR(100),
    SG_ESTADO CHAR(2)
) ON RG_ENDERECO;
GO

-- FINANCEIRO / LIMITE

CREATE TABLE TB_CONTA(
    ID_CONTA BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE BIGINT FOREIGN KEY REFERENCES TB_CLIENTE(ID_CLIENTE),
    NR_AGENCIA VARCHAR(10) NOT NULL,
    NR_CONTA VARCHAR(20) UNIQUE NOT NULL,
    VL_SALDO_ATUAL DECIMAL(18,2) DEFAULT 0.00,
    ID_STATUS_CONTA INT FOREIGN KEY REFERENCES TB_STATUS_CONTA(ID_STATUS_CONTA)
) ON RG_FINANCEIRO;

CREATE TABLE TB_LIMITE_CONTA (
    ID_LIMITE BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_CONTA BIGINT UNIQUE FOREIGN KEY REFERENCES TB_CONTA(ID_CONTA),
    VL_LIMITE_PIX DECIMAL(18,2) DEFAULT 1000.00,
    VL_LIM_CREDITO DECIMAL(18,2) DEFAULT 0.00
) ON RG_FINANCEIRO;
GO

-- AUDITORIA E MOVIMENTACAO

CREATE TABLE TB_TRANSACAO(
    ID_TRANSACAO BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_CONTA_ORIGEM BIGINT FOREIGN KEY REFERENCES TB_CONTA(ID_CONTA),
    ID_CONTA_DESTINO BIGINT FOREIGN KEY REFERENCES TB_CONTA(ID_CONTA), 
    VL_TRANSACAO DECIMAL(18,2) NOT NULL,
    DT_TRANSACAO DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    ID_TIPO_TRANS INT FOREIGN KEY REFERENCES TB_TIPO_TRANSACAO(ID_TIPO_TRANSACAO),
    DS_CHAVE_PIX VARCHAR(100)
) ON RG_TRANSACAO;

CREATE TABLE TB_LOG_AUDITORIA(
    ID_LOG BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO_SIST VARCHAR(60),
    DS_ACAO VARCHAR(100),
    DS_TABELA VARCHAR(128),
    DS_VALOR_ANTIGO NVARCHAR(MAX),
    DS_VALOR_RECENTE NVARCHAR(MAX),
    DT_REGISTRO DATETIME DEFAULT GETDATE()
) ON RG_AUDITORIA;
GO

-- PROCEDURE DE NEGOCIO

CREATE PROCEDURE PR_REALIZAR_TRANSFERENCIA
    @ID_ORIGEM BIGINT,
    @ID_DESTINO BIGINT,
    @VALOR DECIMAL(18,2),
    @ID_TIPO_TRANS INT,
    @CHAVE_PIX VARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SALDO_ORIGEM DECIMAL(18,2), @STATUS_ORIGEM INT, @STATUS_DESTINO INT;

    BEGIN TRY
        BEGIN TRANSACTION;

-- VALIDACOES DE ENTRADA

        IF @VALOR <= 0 THROW 50000, 'O valor deve ser maior que zero.', 1;

-- BLOQUEIO DE LEITURA

        SELECT @SALDO_ORIGEM = VL_SALDO_ATUAL, @STATUS_ORIGEM = ID_STATUS_CONTA
        FROM TB_CONTA WITH (UPDLOCK) 
        WHERE ID_CONTA = @ID_ORIGEM;

        SELECT @STATUS_DESTINO = ID_STATUS_CONTA
        FROM TB_CONTA 
        WHERE ID_CONTA = @ID_DESTINO;

-- VALIDACOES DE REGRA DE NEGOCIO

        IF @STATUS_ORIGEM != 1 OR @STATUS_DESTINO != 1
            THROW 50001, 'Uma das contas não está ativa.', 1;

        IF @SALDO_ORIGEM < @VALOR 
            THROW 50002, 'Saldo insuficiente para a transação.', 1;
        
-- ATUALIZACAO DE SALDO

        UPDATE TB_CONTA SET VL_SALDO_ATUAL -= @VALOR WHERE ID_CONTA = @ID_ORIGEM;
        UPDATE TB_CONTA SET VL_SALDO_ATUAL += @VALOR WHERE ID_CONTA = @ID_DESTINO;

-- REGISTRO HISTORICO

        INSERT INTO TB_TRANSACAO (ID_CONTA_ORIGEM, ID_CONTA_DESTINO, VL_TRANSACAO, ID_TIPO_TRANS, DS_CHAVE_PIX)
        VALUES (@ID_ORIGEM, @ID_DESTINO, @VALOR, @ID_TIPO_TRANS, @CHAVE_PIX);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW; 
    END CATCH
END;
GO
USE CORE_BANK;
GO

-- EXTRATO

CREATE VIEW VW_EXTRATO_DETALHADO AS
SELECT 
    T.DT_TRANSACAO AS [Data/Hora],
    TT.DS_TIPO_TRANSACAO AS [Tipo],
    C_ORIGEM.NM_CLIENTE AS [Remetente],
    ACC_ORIGEM.NR_CONTA AS [Conta Origem],
    C_DESTINO.NM_CLIENTE AS [Destinatário],
    ACC_DESTINO.NR_CONTA AS [Conta Destino],
    T.VL_TRANSACAO AS [Valor],
    ISNULL(T.DS_CHAVE_PIX, '---') AS [Chave PIX]
FROM TB_TRANSACAO T
INNER JOIN TB_TIPO_TRANSACAO TT 
    ON T.ID_TIPO_TRANS = TT.ID_TIPO_TRANSACAO

-- PEGAR DADOS DA CONTA, CLIENTE, ORIGEM

INNER JOIN TB_CONTA ACC_ORIGEM 
    ON T.ID_CONTA_ORIGEM = ACC_ORIGEM.ID_CONTA
INNER JOIN TB_CLIENTE C_ORIGEM 
    ON ACC_ORIGEM.ID_CLIENTE = C_ORIGEM.ID_CLIENTE

-- PEGAR DADOS DA CONTA, CLIENTE, DESTINO

INNER JOIN TB_CONTA ACC_DESTINO 
    ON T.ID_CONTA_DESTINO = ACC_DESTINO.ID_CONTA
INNER JOIN TB_CLIENTE C_DESTINO 
    ON ACC_DESTINO.ID_CLIENTE = C_DESTINO.ID_CLIENTE;
GO

-- VER AS ULTIMAS TRANSFERÊNCIAS FEITAS PELO PACOTE PYTHON

SELECT TOP 50 * FROM VW_EXTRATO_DETALHADO 
ORDER BY [Data/Hora] DESC;


-- RELATORIO

CREATE PROCEDURE PR_RELATORIO_CONSOLIDADO_CONTA
    @ID_CONTA BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    -- VARIAVEIS PARA ARMAZENAR CALCULO

    DECLARE @TotalEntradas DECIMAL(18,2);
    DECLARE @TotalSaidas DECIMAL(18,2);
    DECLARE @QtdTransacoes INT;

    -- SOMA TODAS AS ENTRADAS

    SELECT @TotalEntradas = ISNULL(SUM(VL_TRANSACAO), 0)
    FROM TB_TRANSACAO 
    WHERE ID_CONTA_DESTINO = @ID_CONTA;

    -- SOMA TODAS AS SAIDAS

    SELECT @TotalSaidas = ISNULL(SUM(VL_TRANSACAO), 0)
    FROM TB_TRANSACAO 
    WHERE ID_CONTA_ORIGEM = @ID_CONTA;

    -- CONTAGEM TOTAL DE MOVIMENTOS NA CONTA

    SELECT @QtdTransacoes = COUNT(*)
    FROM TB_TRANSACAO
    WHERE ID_CONTA_ORIGEM = @ID_CONTA OR ID_CONTA_DESTINO = @ID_CONTA;

    -- RESULTADO FINAL

    SELECT 
        C.NM_CLIENTE AS [Cliente],
        ACC.NR_AGENCIA AS [Agência],
        ACC.NR_CONTA AS [Conta],
        SC.DS_STATUS_CONTA AS [Status],
        @TotalEntradas AS [Total Recebido (+)],
        @TotalSaidas AS [Total Enviado (-)],
        (@TotalEntradas - @TotalSaidas) AS [Fluxo Líquido],
        ACC.VL_SALDO_ATUAL AS [Saldo Atual em Conta],
        @QtdTransacoes AS [Total de Operações]
    FROM TB_CONTA ACC
    INNER JOIN TB_CLIENTE C ON ACC.ID_CLIENTE = C.ID_CLIENTE
    INNER JOIN TB_STATUS_CONTA SC ON ACC.ID_STATUS_CONTA = SC.ID_STATUS_CONTA
    WHERE ACC.ID_CONTA = @ID_CONTA;
END;
GO

-- TESTE PAR CONTA

EXEC PR_RELATORIO_CONSOLIDADO_CONTA @ID_CONTA = 5;

-- INDICES DE PERFORMACE

USE CORE_BANK;
GO

-- INDICE PARA ACELERAR A BUSCA POR MOVIMENTAÇÕES DE CONTA

-- É ESSENCIAL PARA A PR_RELATORIO_CONSOLIDADO_CONTA

CREATE NONCLUSTERED INDEX IX_TRANSACAO_CONTA_ORIGEM 
ON TB_TRANSACAO (ID_CONTA_ORIGEM)
INCLUDE (VL_TRANSACAO, DT_TRANSACAO);

CREATE NONCLUSTERED INDEX IX_TRANSACAO_CONTA_DESTINO 
ON TB_TRANSACAO (ID_CONTA_DESTINO)
INCLUDE (VL_TRANSACAO, DT_TRANSACAO);

-- INDICE PARA BUSCA DE DATAS

CREATE NONCLUSTERED INDEX IX_TRANSACAO_DATA 
ON TB_TRANSACAO (DT_TRANSACAO);

-- INDICE PARA FAZER A BUSCA DE CLIENTES

CREATE NONCLUSTERED INDEX IX_CONTA_CLIENTE 
ON TB_CONTA (ID_CLIENTE);

-- INDICE PARA BUSCA RAPIDA DE CPF E CNPJ 

CREATE NONCLUSTERED INDEX IX_CLIENTE_DOCUMENTO 
ON TB_CLIENTE (NR_CPF_CNPJ);
GO

-- VERIFICAR SE ESTÁ FUNCIONANDO CORRETAMENTE
-- PODE TENTAR RODAR ANTES DO RELATORIO

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

-- EXECUTA O RELATORIO

EXEC PR_RELATORIO_CONSOLIDADO_CONTA @ID_CONTA = 1;

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;


-- CONFIGURAÇÃO DE SEGURANÇA USUÁRIO DA APLICAÇÃO

USE master;
GO

-- VERIFICA SE O LOGIN JA EXISTE ANTES DE CRIAR

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'AppPythonUser')
BEGIN
    CREATE LOGIN AppPythonUser WITH PASSWORD = 'SenhaForte#2026';
END
GO

USE CORE_BANK;
GO

-- CRIA UM USUARIO VINCULADO AO LOGIN

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'AppPythonUser')
BEGIN
    CREATE USER AppPythonUser FOR LOGIN AppPythonUser;
END
GO

-- ATRIBUICOES DE PERMISSOES MINIMAS

GRANT SELECT TO AppPythonUser;
GRANT INSERT, UPDATE ON OBJECT::dbo.TB_CLIENTE TO AppPythonUser;
GRANT INSERT, UPDATE ON OBJECT::dbo.TB_ENDERECO TO AppPythonUser;
GRANT INSERT, UPDATE ON OBJECT::dbo.TB_CONTA TO AppPythonUser;
GRANT INSERT, UPDATE ON OBJECT::dbo.TB_LIMITE_CONTA TO AppPythonUser;
GRANT EXECUTE ON OBJECT::dbo.PR_REALIZAR_TRANSFERENCIA TO AppPythonUser;
GRANT EXECUTE ON OBJECT::dbo.PR_RELATORIO_CONSOLIDADO_CONTA TO AppPythonUser;
GO

-- CRIAR UMA TRIGGER DE AUTIDORIA
