USE master;
GO

-- FORÇA A DESCONEXAO DO USUARIO

ALTER DATABASE CORE_BANK SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

-- RESTAURA O BANCO

RESTORE DATABASE CORE_BANK
FROM DISK = N'C:\SQLData\CORE_BANK_FULL.bak'
WITH 
    REPLACE,        -- SOBRESCREVE O BANCO AUTAL, CASO ELE EXISTA
    RECOVERY,       -- DEIXA O BANCO PRONTO PARA USAR ONLINE
    STATS = 10;
GO

-- VOLTA O BANCO PARA ACESSO MULTIPLO

ALTER DATABASE CORE_BANK SET MULTI_USER;
GO

